name: testes
on:
  pull_request:
    branches:
      - main
jobs:
  teste:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: |
          cd src/findriver
          yarn install
          echo "export const environment = {SUPABASE_URL: '${{ secrets.SUPABASE_URL }}', SUPABASE_ANON_KEY: '${{ secrets.SUPABASE_ANON_KEY }}'}" > .env.js
      - run: |
          cd src/findriver
          yarn
          yarn test
